muscles = [
    "Ombro Esquerdo",
    "Ombro Direito",
    "Ombros (Ambos)",
    "Joelho Esquerdo",
    "Joelho Direito",
    "Joelhos (Ambos)",
    "Tornozelo Esquerdo",
    "Tornozelo Direito",
    "Tornozelos (Ambos)",
    "Cotovelo Esquerdo",
    "Cotovelo Direito",
    "Punho Esquerdo",
    "Punho Direito",
    "Coluna Lombar",
    "Coluna Cervical",
    "Quadril Esquerdo",
    "Quadril Direito",
    "Pé Esquerdo",
    "Pé Direito",
    "Pescoço",
    "Cabeça",
    "Outro",
]
